/* generated: DEFINES /usr/include/X11/X.h gen */
#define DEFINES_CONSTS \
STD2_CONST("X_H", INT, X_H) \
STD2_CONST("X_PROTOCOL", INT, X_PROTOCOL) \
STD2_CONST("X_PROTOCOL_REVISION", INT, X_PROTOCOL_REVISION) \
STD2_CONST("_XTYPEDEF_XID", INT, _XTYPEDEF_XID) \
STD2_CONST("_XTYPEDEF_MASK", INT, _XTYPEDEF_MASK) \
STD2_CONST("_XTYPEDEF_ATOM", INT, _XTYPEDEF_ATOM) \
STD2_CONST("_XTYPEDEF_XID", INT, _XTYPEDEF_XID) \
STD2_CONST("_XTYPEDEF_MASK", INT, _XTYPEDEF_MASK) \
STD2_CONST("_XTYPEDEF_ATOM", INT, _XTYPEDEF_ATOM) \
STD2_CONST("_XTYPEDEF_FONT", INT, _XTYPEDEF_FONT) \
STD2_CONST("None", INT, None) \
STD2_CONST("ParentRelative", INT, ParentRelative) \
STD2_CONST("CopyFromParent", INT, CopyFromParent) \
STD2_CONST("PointerWindow", INT, PointerWindow) \
STD2_CONST("InputFocus", INT, InputFocus) \
STD2_CONST("PointerRoot", INT, PointerRoot) \
STD2_CONST("AnyPropertyType", INT, AnyPropertyType) \
STD2_CONST("AnyKey", INT, AnyKey) \
STD2_CONST("AnyButton", INT, AnyButton) \
STD2_CONST("AllTemporary", INT, AllTemporary) \
STD2_CONST("CurrentTime", INT, CurrentTime) \
STD2_CONST("NoSymbol", INT, NoSymbol) \
STD2_CONST("NoEventMask", INT, NoEventMask) \
STD2_CONST("KeyPressMask", INT, KeyPressMask) \
STD2_CONST("KeyReleaseMask", INT, KeyReleaseMask) \
STD2_CONST("ButtonPressMask", INT, ButtonPressMask) \
STD2_CONST("ButtonReleaseMask", INT, ButtonReleaseMask) \
STD2_CONST("EnterWindowMask", INT, EnterWindowMask) \
STD2_CONST("LeaveWindowMask", INT, LeaveWindowMask) \
STD2_CONST("PointerMotionMask", INT, PointerMotionMask) \
STD2_CONST("PointerMotionHintMask", INT, PointerMotionHintMask) \
STD2_CONST("Button1MotionMask", INT, Button1MotionMask) \
STD2_CONST("Button2MotionMask", INT, Button2MotionMask) \
STD2_CONST("Button3MotionMask", INT, Button3MotionMask) \
STD2_CONST("Button4MotionMask", INT, Button4MotionMask) \
STD2_CONST("Button5MotionMask", INT, Button5MotionMask) \
STD2_CONST("ButtonMotionMask", INT, ButtonMotionMask) \
STD2_CONST("KeymapStateMask", INT, KeymapStateMask) \
STD2_CONST("ExposureMask", INT, ExposureMask) \
STD2_CONST("VisibilityChangeMask", INT, VisibilityChangeMask) \
STD2_CONST("StructureNotifyMask", INT, StructureNotifyMask) \
STD2_CONST("ResizeRedirectMask", INT, ResizeRedirectMask) \
STD2_CONST("SubstructureNotifyMask", INT, SubstructureNotifyMask) \
STD2_CONST("SubstructureRedirectMask", INT, SubstructureRedirectMask) \
STD2_CONST("FocusChangeMask", INT, FocusChangeMask) \
STD2_CONST("PropertyChangeMask", INT, PropertyChangeMask) \
STD2_CONST("ColormapChangeMask", INT, ColormapChangeMask) \
STD2_CONST("OwnerGrabButtonMask", INT, OwnerGrabButtonMask) \
STD2_CONST("KeyPress", INT, KeyPress) \
STD2_CONST("KeyRelease", INT, KeyRelease) \
STD2_CONST("ButtonPress", INT, ButtonPress) \
STD2_CONST("ButtonRelease", INT, ButtonRelease) \
STD2_CONST("MotionNotify", INT, MotionNotify) \
STD2_CONST("EnterNotify", INT, EnterNotify) \
STD2_CONST("LeaveNotify", INT, LeaveNotify) \
STD2_CONST("FocusIn", INT, FocusIn) \
STD2_CONST("FocusOut", INT, FocusOut) \
STD2_CONST("KeymapNotify", INT, KeymapNotify) \
STD2_CONST("Expose", INT, Expose) \
STD2_CONST("GraphicsExpose", INT, GraphicsExpose) \
STD2_CONST("NoExpose", INT, NoExpose) \
STD2_CONST("VisibilityNotify", INT, VisibilityNotify) \
STD2_CONST("CreateNotify", INT, CreateNotify) \
STD2_CONST("DestroyNotify", INT, DestroyNotify) \
STD2_CONST("UnmapNotify", INT, UnmapNotify) \
STD2_CONST("MapNotify", INT, MapNotify) \
STD2_CONST("MapRequest", INT, MapRequest) \
STD2_CONST("ReparentNotify", INT, ReparentNotify) \
STD2_CONST("ConfigureNotify", INT, ConfigureNotify) \
STD2_CONST("ConfigureRequest", INT, ConfigureRequest) \
STD2_CONST("GravityNotify", INT, GravityNotify) \
STD2_CONST("ResizeRequest", INT, ResizeRequest) \
STD2_CONST("CirculateNotify", INT, CirculateNotify) \
STD2_CONST("CirculateRequest", INT, CirculateRequest) \
STD2_CONST("PropertyNotify", INT, PropertyNotify) \
STD2_CONST("SelectionClear", INT, SelectionClear) \
STD2_CONST("SelectionRequest", INT, SelectionRequest) \
STD2_CONST("SelectionNotify", INT, SelectionNotify) \
STD2_CONST("ColormapNotify", INT, ColormapNotify) \
STD2_CONST("ClientMessage", INT, ClientMessage) \
STD2_CONST("MappingNotify", INT, MappingNotify) \
STD2_CONST("GenericEvent", INT, GenericEvent) \
STD2_CONST("LASTEvent", INT, LASTEvent) \
STD2_CONST("ShiftMask", INT, ShiftMask) \
STD2_CONST("LockMask", INT, LockMask) \
STD2_CONST("ControlMask", INT, ControlMask) \
STD2_CONST("Mod1Mask", INT, Mod1Mask) \
STD2_CONST("Mod2Mask", INT, Mod2Mask) \
STD2_CONST("Mod3Mask", INT, Mod3Mask) \
STD2_CONST("Mod4Mask", INT, Mod4Mask) \
STD2_CONST("Mod5Mask", INT, Mod5Mask) \
STD2_CONST("ShiftMapIndex", INT, ShiftMapIndex) \
STD2_CONST("LockMapIndex", INT, LockMapIndex) \
STD2_CONST("ControlMapIndex", INT, ControlMapIndex) \
STD2_CONST("Mod1MapIndex", INT, Mod1MapIndex) \
STD2_CONST("Mod2MapIndex", INT, Mod2MapIndex) \
STD2_CONST("Mod3MapIndex", INT, Mod3MapIndex) \
STD2_CONST("Mod4MapIndex", INT, Mod4MapIndex) \
STD2_CONST("Mod5MapIndex", INT, Mod5MapIndex) \
STD2_CONST("Button1Mask", INT, Button1Mask) \
STD2_CONST("Button2Mask", INT, Button2Mask) \
STD2_CONST("Button3Mask", INT, Button3Mask) \
STD2_CONST("Button4Mask", INT, Button4Mask) \
STD2_CONST("Button5Mask", INT, Button5Mask) \
STD2_CONST("AnyModifier", INT, AnyModifier) \
STD2_CONST("Button1", INT, Button1) \
STD2_CONST("Button2", INT, Button2) \
STD2_CONST("Button3", INT, Button3) \
STD2_CONST("Button4", INT, Button4) \
STD2_CONST("Button5", INT, Button5) \
STD2_CONST("NotifyNormal", INT, NotifyNormal) \
STD2_CONST("NotifyGrab", INT, NotifyGrab) \
STD2_CONST("NotifyUngrab", INT, NotifyUngrab) \
STD2_CONST("NotifyWhileGrabbed", INT, NotifyWhileGrabbed) \
STD2_CONST("NotifyHint", INT, NotifyHint) \
STD2_CONST("NotifyAncestor", INT, NotifyAncestor) \
STD2_CONST("NotifyVirtual", INT, NotifyVirtual) \
STD2_CONST("NotifyInferior", INT, NotifyInferior) \
STD2_CONST("NotifyNonlinear", INT, NotifyNonlinear) \
STD2_CONST("NotifyNonlinearVirtual", INT, NotifyNonlinearVirtual) \
STD2_CONST("NotifyPointer", INT, NotifyPointer) \
STD2_CONST("NotifyPointerRoot", INT, NotifyPointerRoot) \
STD2_CONST("NotifyDetailNone", INT, NotifyDetailNone) \
STD2_CONST("VisibilityUnobscured", INT, VisibilityUnobscured) \
STD2_CONST("VisibilityPartiallyObscured", INT, VisibilityPartiallyObscured) \
STD2_CONST("VisibilityFullyObscured", INT, VisibilityFullyObscured) \
STD2_CONST("PlaceOnTop", INT, PlaceOnTop) \
STD2_CONST("PlaceOnBottom", INT, PlaceOnBottom) \
STD2_CONST("FamilyInternet", INT, FamilyInternet) \
STD2_CONST("FamilyDECnet", INT, FamilyDECnet) \
STD2_CONST("FamilyChaos", INT, FamilyChaos) \
STD2_CONST("FamilyInternet6", INT, FamilyInternet6) \
STD2_CONST("FamilyServerInterpreted", INT, FamilyServerInterpreted) \
STD2_CONST("PropertyNewValue", INT, PropertyNewValue) \
STD2_CONST("PropertyDelete", INT, PropertyDelete) \
STD2_CONST("ColormapUninstalled", INT, ColormapUninstalled) \
STD2_CONST("ColormapInstalled", INT, ColormapInstalled) \
STD2_CONST("GrabModeSync", INT, GrabModeSync) \
STD2_CONST("GrabModeAsync", INT, GrabModeAsync) \
STD2_CONST("GrabSuccess", INT, GrabSuccess) \
STD2_CONST("AlreadyGrabbed", INT, AlreadyGrabbed) \
STD2_CONST("GrabInvalidTime", INT, GrabInvalidTime) \
STD2_CONST("GrabNotViewable", INT, GrabNotViewable) \
STD2_CONST("GrabFrozen", INT, GrabFrozen) \
STD2_CONST("AsyncPointer", INT, AsyncPointer) \
STD2_CONST("SyncPointer", INT, SyncPointer) \
STD2_CONST("ReplayPointer", INT, ReplayPointer) \
STD2_CONST("AsyncKeyboard", INT, AsyncKeyboard) \
STD2_CONST("SyncKeyboard", INT, SyncKeyboard) \
STD2_CONST("ReplayKeyboard", INT, ReplayKeyboard) \
STD2_CONST("AsyncBoth", INT, AsyncBoth) \
STD2_CONST("SyncBoth", INT, SyncBoth) \
STD2_CONST("RevertToNone", INT, RevertToNone) \
STD2_CONST("RevertToPointerRoot", INT, RevertToPointerRoot) \
STD2_CONST("RevertToParent", INT, RevertToParent) \
STD2_CONST("Success", INT, Success) \
STD2_CONST("BadRequest", INT, BadRequest) \
STD2_CONST("BadValue", INT, BadValue) \
STD2_CONST("BadWindow", INT, BadWindow) \
STD2_CONST("BadPixmap", INT, BadPixmap) \
STD2_CONST("BadAtom", INT, BadAtom) \
STD2_CONST("BadCursor", INT, BadCursor) \
STD2_CONST("BadFont", INT, BadFont) \
STD2_CONST("BadMatch", INT, BadMatch) \
STD2_CONST("BadDrawable", INT, BadDrawable) \
STD2_CONST("BadAccess", INT, BadAccess) \
STD2_CONST("BadAlloc", INT, BadAlloc) \
STD2_CONST("BadColor", INT, BadColor) \
STD2_CONST("BadGC", INT, BadGC) \
STD2_CONST("BadIDChoice", INT, BadIDChoice) \
STD2_CONST("BadName", INT, BadName) \
STD2_CONST("BadLength", INT, BadLength) \
STD2_CONST("BadImplementation", INT, BadImplementation) \
STD2_CONST("FirstExtensionError", INT, FirstExtensionError) \
STD2_CONST("LastExtensionError", INT, LastExtensionError) \
STD2_CONST("InputOutput", INT, InputOutput) \
STD2_CONST("InputOnly", INT, InputOnly) \
STD2_CONST("CWBackPixmap", INT, CWBackPixmap) \
STD2_CONST("CWBackPixel", INT, CWBackPixel) \
STD2_CONST("CWBorderPixmap", INT, CWBorderPixmap) \
STD2_CONST("CWBorderPixel", INT, CWBorderPixel) \
STD2_CONST("CWBitGravity", INT, CWBitGravity) \
STD2_CONST("CWWinGravity", INT, CWWinGravity) \
STD2_CONST("CWBackingStore", INT, CWBackingStore) \
STD2_CONST("CWBackingPlanes", INT, CWBackingPlanes) \
STD2_CONST("CWBackingPixel", INT, CWBackingPixel) \
STD2_CONST("CWOverrideRedirect", INT, CWOverrideRedirect) \
STD2_CONST("CWSaveUnder", INT, CWSaveUnder) \
STD2_CONST("CWEventMask", INT, CWEventMask) \
STD2_CONST("CWDontPropagate", INT, CWDontPropagate) \
STD2_CONST("CWColormap", INT, CWColormap) \
STD2_CONST("CWCursor", INT, CWCursor) \
STD2_CONST("CWX", INT, CWX) \
STD2_CONST("CWY", INT, CWY) \
STD2_CONST("CWWidth", INT, CWWidth) \
STD2_CONST("CWHeight", INT, CWHeight) \
STD2_CONST("CWBorderWidth", INT, CWBorderWidth) \
STD2_CONST("CWSibling", INT, CWSibling) \
STD2_CONST("CWStackMode", INT, CWStackMode) \
STD2_CONST("ForgetGravity", INT, ForgetGravity) \
STD2_CONST("NorthWestGravity", INT, NorthWestGravity) \
STD2_CONST("NorthGravity", INT, NorthGravity) \
STD2_CONST("NorthEastGravity", INT, NorthEastGravity) \
STD2_CONST("WestGravity", INT, WestGravity) \
STD2_CONST("CenterGravity", INT, CenterGravity) \
STD2_CONST("EastGravity", INT, EastGravity) \
STD2_CONST("SouthWestGravity", INT, SouthWestGravity) \
STD2_CONST("SouthGravity", INT, SouthGravity) \
STD2_CONST("SouthEastGravity", INT, SouthEastGravity) \
STD2_CONST("StaticGravity", INT, StaticGravity) \
STD2_CONST("UnmapGravity", INT, UnmapGravity) \
STD2_CONST("NotUseful", INT, NotUseful) \
STD2_CONST("WhenMapped", INT, WhenMapped) \
STD2_CONST("Always", INT, Always) \
STD2_CONST("IsUnmapped", INT, IsUnmapped) \
STD2_CONST("IsUnviewable", INT, IsUnviewable) \
STD2_CONST("IsViewable", INT, IsViewable) \
STD2_CONST("SetModeInsert", INT, SetModeInsert) \
STD2_CONST("SetModeDelete", INT, SetModeDelete) \
STD2_CONST("DestroyAll", INT, DestroyAll) \
STD2_CONST("RetainPermanent", INT, RetainPermanent) \
STD2_CONST("RetainTemporary", INT, RetainTemporary) \
STD2_CONST("Above", INT, Above) \
STD2_CONST("Below", INT, Below) \
STD2_CONST("TopIf", INT, TopIf) \
STD2_CONST("BottomIf", INT, BottomIf) \
STD2_CONST("Opposite", INT, Opposite) \
STD2_CONST("RaiseLowest", INT, RaiseLowest) \
STD2_CONST("LowerHighest", INT, LowerHighest) \
STD2_CONST("PropModeReplace", INT, PropModeReplace) \
STD2_CONST("PropModePrepend", INT, PropModePrepend) \
STD2_CONST("PropModeAppend", INT, PropModeAppend) \
STD2_CONST("GXclear", INT, GXclear) \
STD2_CONST("GXand", INT, GXand) \
STD2_CONST("GXandReverse", INT, GXandReverse) \
STD2_CONST("GXcopy", INT, GXcopy) \
STD2_CONST("GXandInverted", INT, GXandInverted) \
STD2_CONST("GXnoop", INT, GXnoop) \
STD2_CONST("GXxor", INT, GXxor) \
STD2_CONST("GXor", INT, GXor) \
STD2_CONST("GXnor", INT, GXnor) \
STD2_CONST("GXequiv", INT, GXequiv) \
STD2_CONST("GXinvert", INT, GXinvert) \
STD2_CONST("GXorReverse", INT, GXorReverse) \
STD2_CONST("GXcopyInverted", INT, GXcopyInverted) \
STD2_CONST("GXorInverted", INT, GXorInverted) \
STD2_CONST("GXnand", INT, GXnand) \
STD2_CONST("GXset", INT, GXset) \
STD2_CONST("LineSolid", INT, LineSolid) \
STD2_CONST("LineOnOffDash", INT, LineOnOffDash) \
STD2_CONST("LineDoubleDash", INT, LineDoubleDash) \
STD2_CONST("CapNotLast", INT, CapNotLast) \
STD2_CONST("CapButt", INT, CapButt) \
STD2_CONST("CapRound", INT, CapRound) \
STD2_CONST("CapProjecting", INT, CapProjecting) \
STD2_CONST("JoinMiter", INT, JoinMiter) \
STD2_CONST("JoinRound", INT, JoinRound) \
STD2_CONST("JoinBevel", INT, JoinBevel) \
STD2_CONST("FillSolid", INT, FillSolid) \
STD2_CONST("FillTiled", INT, FillTiled) \
STD2_CONST("FillStippled", INT, FillStippled) \
STD2_CONST("FillOpaqueStippled", INT, FillOpaqueStippled) \
STD2_CONST("EvenOddRule", INT, EvenOddRule) \
STD2_CONST("WindingRule", INT, WindingRule) \
STD2_CONST("ClipByChildren", INT, ClipByChildren) \
STD2_CONST("IncludeInferiors", INT, IncludeInferiors) \
STD2_CONST("Unsorted", INT, Unsorted) \
STD2_CONST("YSorted", INT, YSorted) \
STD2_CONST("YXSorted", INT, YXSorted) \
STD2_CONST("YXBanded", INT, YXBanded) \
STD2_CONST("CoordModeOrigin", INT, CoordModeOrigin) \
STD2_CONST("CoordModePrevious", INT, CoordModePrevious) \
STD2_CONST("Complex", INT, Complex) \
STD2_CONST("Nonconvex", INT, Nonconvex) \
STD2_CONST("Convex", INT, Convex) \
STD2_CONST("ArcChord", INT, ArcChord) \
STD2_CONST("ArcPieSlice", INT, ArcPieSlice) \
STD2_CONST("GCFunction", INT, GCFunction) \
STD2_CONST("GCPlaneMask", INT, GCPlaneMask) \
STD2_CONST("GCForeground", INT, GCForeground) \
STD2_CONST("GCBackground", INT, GCBackground) \
STD2_CONST("GCLineWidth", INT, GCLineWidth) \
STD2_CONST("GCLineStyle", INT, GCLineStyle) \
STD2_CONST("GCCapStyle", INT, GCCapStyle) \
STD2_CONST("GCJoinStyle", INT, GCJoinStyle) \
STD2_CONST("GCFillStyle", INT, GCFillStyle) \
STD2_CONST("GCFillRule", INT, GCFillRule) \
STD2_CONST("GCTile", INT, GCTile) \
STD2_CONST("GCStipple", INT, GCStipple) \
STD2_CONST("GCTileStipXOrigin", INT, GCTileStipXOrigin) \
STD2_CONST("GCTileStipYOrigin", INT, GCTileStipYOrigin) \
STD2_CONST("GCFont", INT, GCFont) \
STD2_CONST("GCSubwindowMode", INT, GCSubwindowMode) \
STD2_CONST("GCGraphicsExposures", INT, GCGraphicsExposures) \
STD2_CONST("GCClipXOrigin", INT, GCClipXOrigin) \
STD2_CONST("GCClipYOrigin", INT, GCClipYOrigin) \
STD2_CONST("GCClipMask", INT, GCClipMask) \
STD2_CONST("GCDashOffset", INT, GCDashOffset) \
STD2_CONST("GCDashList", INT, GCDashList) \
STD2_CONST("GCArcMode", INT, GCArcMode) \
STD2_CONST("GCLastBit", INT, GCLastBit) \
STD2_CONST("FontLeftToRight", INT, FontLeftToRight) \
STD2_CONST("FontRightToLeft", INT, FontRightToLeft) \
STD2_CONST("FontChange", INT, FontChange) \
STD2_CONST("XYBitmap", INT, XYBitmap) \
STD2_CONST("XYPixmap", INT, XYPixmap) \
STD2_CONST("ZPixmap", INT, ZPixmap) \
STD2_CONST("AllocNone", INT, AllocNone) \
STD2_CONST("AllocAll", INT, AllocAll) \
STD2_CONST("DoRed", INT, DoRed) \
STD2_CONST("DoGreen", INT, DoGreen) \
STD2_CONST("DoBlue", INT, DoBlue) \
STD2_CONST("CursorShape", INT, CursorShape) \
STD2_CONST("TileShape", INT, TileShape) \
STD2_CONST("StippleShape", INT, StippleShape) \
STD2_CONST("AutoRepeatModeOff", INT, AutoRepeatModeOff) \
STD2_CONST("AutoRepeatModeOn", INT, AutoRepeatModeOn) \
STD2_CONST("AutoRepeatModeDefault", INT, AutoRepeatModeDefault) \
STD2_CONST("LedModeOff", INT, LedModeOff) \
STD2_CONST("LedModeOn", INT, LedModeOn) \
STD2_CONST("KBKeyClickPercent", INT, KBKeyClickPercent) \
STD2_CONST("KBBellPercent", INT, KBBellPercent) \
STD2_CONST("KBBellPitch", INT, KBBellPitch) \
STD2_CONST("KBBellDuration", INT, KBBellDuration) \
STD2_CONST("KBLed", INT, KBLed) \
STD2_CONST("KBLedMode", INT, KBLedMode) \
STD2_CONST("KBKey", INT, KBKey) \
STD2_CONST("KBAutoRepeatMode", INT, KBAutoRepeatMode) \
STD2_CONST("MappingSuccess", INT, MappingSuccess) \
STD2_CONST("MappingBusy", INT, MappingBusy) \
STD2_CONST("MappingFailed", INT, MappingFailed) \
STD2_CONST("MappingModifier", INT, MappingModifier) \
STD2_CONST("MappingKeyboard", INT, MappingKeyboard) \
STD2_CONST("MappingPointer", INT, MappingPointer) \
STD2_CONST("DontPreferBlanking", INT, DontPreferBlanking) \
STD2_CONST("PreferBlanking", INT, PreferBlanking) \
STD2_CONST("DefaultBlanking", INT, DefaultBlanking) \
STD2_CONST("DisableScreenSaver", INT, DisableScreenSaver) \
STD2_CONST("DisableScreenInterval", INT, DisableScreenInterval) \
STD2_CONST("DontAllowExposures", INT, DontAllowExposures) \
STD2_CONST("AllowExposures", INT, AllowExposures) \
STD2_CONST("DefaultExposures", INT, DefaultExposures) \
STD2_CONST("ScreenSaverReset", INT, ScreenSaverReset) \
STD2_CONST("ScreenSaverActive", INT, ScreenSaverActive) \
STD2_CONST("HostInsert", INT, HostInsert) \
STD2_CONST("HostDelete", INT, HostDelete) \
STD2_CONST("EnableAccess", INT, EnableAccess) \
STD2_CONST("DisableAccess", INT, DisableAccess) \
STD2_CONST("StaticGray", INT, StaticGray) \
STD2_CONST("GrayScale", INT, GrayScale) \
STD2_CONST("StaticColor", INT, StaticColor) \
STD2_CONST("PseudoColor", INT, PseudoColor) \
STD2_CONST("TrueColor", INT, TrueColor) \
STD2_CONST("DirectColor", INT, DirectColor) \
STD2_CONST("LSBFirst", INT, LSBFirst) \
STD2_CONST("MSBFirst", INT, MSBFirst) \

